export const enTranslations = {
    didNotRegisterYet: 'Did not register yet?',
    insertEmail: 'Insert e-mail',
    emailIsRequired: 'E-mail is required.',
    emailIsInWrongFormat: 'E-mail is in wrong format.',
    invalidCredentials: 'Invalid credentials',
    insertPassword: 'Insert e-mail',
    passwordIsRequired: 'Password is required.',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    forgotPassword: 'Forgot password?',
    password: 'Password',
    nameIsRequired: 'Name is required.',
    insertName: 'Insert name',
    emailAlreadyInUse: 'The email address is already in use by another account.',
    passwordRegEx:
        'Password should contain atleast one digit, one lower case character, one uppercase character and be atleast 8 characters long.',
    register: 'Register',
    alreadyRegistered: 'Already registered?',
    emailReset: 'Password reset email has been sent.',
    emailNotFoundInDB: 'This email address is not found in our database.',
    recoverPW: 'Recover Password',
};

export const nlTranslations = {
    didNotRegisterYet: 'Nog niet geregistreerd?',
    insertEmail: 'Voeg e-mail in',
    emailIsRequired: 'E-mail is verplicht.',
    emailIsInWrongFormat: 'E-mail is in het verkeerde formaat.',
    invalidCredentials: 'Ongeldige inloggegevens',
    insertPassword: 'Voeg paswoord in',
    passwordIsRequired: 'Paswoord is verplicht.',
    signUp: 'Registreer',
    signIn: 'Inloggen',
    forgotPassword: 'Paswoord vergeten?',
    password: 'Paswoord',
    nameIsRequired: 'Naam is verplicht.',
    insertName: 'Voeg naam in',
    emailAlreadyInUse: 'Het e-mail adres is al in gebruik.',
    passwordRegEx:
        'Paswoord moet tenminste 1 cijfer, 1 kleine letter, 1 grote letter bevatten en minimum 8 karakters lang zijn.',
    register: 'Registreer',
    alreadyRegistered: 'Al geregistreerd?',
    emailReset: 'E-mail om het paswoord te resetten is verstuurd.',
    emailNotFoundInDB: 'Dit e-mail adres is niet teruggevonden in onze database.',
    recoverPW: 'Herstel paswoord',
};

export const frTranslations = {
    didNotRegisterYet: 'Nog niet geregistreerd?',
    insertEmail: 'Insert e-mail',
    emailIsRequired: 'E-mail is required.',
    emailIsInWrongFormat: 'E-mail is in wrong format.',
    invalidCredentials: 'Invalid credentials',
    insertPassword: 'Insert e-mail',
    passwordIsRequired: 'Password is required.',
    signUp: 'Sign Up',
    signIn: 'Sign In',
    forgotPassword: 'Forgot password?',
    password: 'Password',
    nameIsRequired: 'Name is required.',
    insertName: 'Insert name',
    emailAlreadyInUse: 'The email address is already in use by another account.',
    passwordRegEx:
        'Password should contain atleast one digit, one lower case character, one uppercase character and be atleast 8 characters long.',
    register: 'Register',
    alreadyRegistered: 'Already registered?',
    emailReset: 'Password reset email has been sent.',
    emailNotFoundInDB: 'This email address is not found in our database.',
    recoverPW: 'Recover Password',
};
